name: rwkv_4neo
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10
  - numpy
  - tqdm
  - pip
  - pip:
    - torch==1.13.1+cu117
    - transformers
    - datasets
    - tiktoken
    - wandb
    - deepspeed==0.7.0
    - pytorch-lightning==1.9.5
